### ISSUE TITLE
Hardcoded processes=1

### ISSUE THREAD

**Issue by srgkm** [joowani/kq#2]
Hi!

Thank you for this package.

Why do you use MP module and hardcode number of workers (1) in a pool?

https://github.com/joowani/kq/blob/master/kq/worker.py#L257

**Comment by joowani** [comment]
No problem! Thank you for your interest.

I use it for enforcing timeouts on jobs (I spawn a child process to do carry out the job and if it hits  the timeout threshold I simply terminate it). I chose processes instead of threads/signals for OS compatibility issues. The pool only has a single process to minimize resources (e.g. file descriptors), and no more than one is needed as a worker processes jobs sequentially.

Thanks
Joohwan

**Comment by joowani** [comment]
Closing ticket. Let me know if you have anymore questions!
